language: julia

# Homebrew no longer bottles for OSX 10.9; request 10.11
matrix:
  include:
    - os: linux
      julia: 0.6
    - os: osx
      julia: 0.6
      osx_image: xcode7.3

addons:
  apt_packages:
    - gfortran

branches:
  only:
    - master

before_install:
  - if [ `uname` == "Linux" ]; then
      unset DY_LIBRARY_PATH;
    julia -E 'Pkg.clone("https://github.com/dpo/Linuxbrew.jl.git"); Pkg.build("Linuxbrew"); using Linuxbrew; Linuxbrew.add("patchelf"); Linuxbrew.add("gcc")';
    fi
  - if [ `uname` == "Darwin" ]; then brew update && brew install gcc; fi
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

install:
  - julia -e 'versioninfo()'
  - julia -E 'Pkg.clone(pwd());'
  - julia -E 'Pkg.build("CUTEst");'

script:
  - julia --check-bounds=yes -E 'Pkg.test("CUTEst"; coverage=true)'

after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'Pkg.clone("https://github.com/JuliaSmoothOptimizers/Krylov.jl"); Pkg.checkout("Krylov", "develop")'
  - julia -e 'cd(Pkg.dir("CUTEst")); include(joinpath("docs", "make.jl"))'
  - julia -e 'cd(Pkg.dir("CUTEst")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
