language: julia

os:
  - linux
  - osx

arch:
  - x64
  - amd64
  # - ppc64le
  - arm64

julia:
  - 1.3
  - 1 # Latest stable
  - nightly

addons:
  apt_packages:
    - gfortran

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # tags

before_install:
  - if [ `uname` == "Linux" ]; then unset DY_LIBRARY_PATH; fi
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: Documentation
      julia: 1
      os: linux
      script:
        - git clone https://bitbucket.org/optrove/sif.git deps/sif
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - export MASTSIF=$PWD/deps/sif; julia --project=docs docs/make.jl
      after_success: skip

after_success:
  - julia -e 'if Sys.islinux()
      using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(process_folder())
    end'
