[sifcollection]
git-tree-sha1 = "447005f21c5764d18f6ace9915318fb802f6c548"
lazy = true

    [[sifcollection.download]]
    url = "https://bitbucket.org/optrove/sif/get/af0980d59a0ad3e9ad250316c6758d07d5892a0a.tar.gz"
    sha256 = "772d38c95657be6283338297dce12c6397117a2702a481284304d8fed78bd539"

[maros-meszaros]
git-tree-sha1 = "0eff5ae5b345db85386f55f672a19c90f23257b2"
lazy = true

    [[maros-meszaros.download]]
    url = "https://bitbucket.org/optrove/maros-meszaros/get/9adfb5707b1e0b83a2e0a26cc8310704ff01b7c1.tar.gz"
    sha256 = "1bdb9df59502c2f24ae23303f70b2edbdf54660c1db88a048c230e4d3ab851c3"

[netlib-lp]
git-tree-sha1 = "545f8c5577a056981a21caf3f53bd7b59cf67410"
lazy = true

    [[netlib-lp.download]]
    url = "https://bitbucket.org/optrove/netlib-lp/get/f83996fca9370b23d8896f134c4dfe7adbaca0ec.tar.gz"
    sha256 = "e5b7d4128a0bde757ac59182228f80a33828ccc62c1764a33de722b096c0dd9a"

[[mingw-w64]]
arch = "x86_64"
git-tree-sha1 = "fdff308295487f361ef6e8dc2d27f5abe8a6eee9"
os = "windows"
lazy = true

    [[mingw-w64.download]]
    sha256 = "fe3f401bc936fbe6af940b26c5e0f266f762a3416f979c706e599b24082dc5c7"
    url = "https://github.com/JuliaLang/PackageCompiler.jl/releases/download/v1.0.0/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.tar.gz"

[[mingw-w64]]
arch = "i686"
git-tree-sha1 = "bc760d8ef1b4840e55a36bd361587b4975af811f"
os = "windows"
lazy = true

    [[mingw-w64.download]]
    sha256 = "ab0abb76384ce9b657141d3a54150d0b865f9c06576caa7901a6c8429c9008e5"
    url = "https://github.com/JuliaLang/PackageCompiler.jl/releases/download/v1.0.0/i686-8.1.0-release-posix-sjlj-rt_v6-rev0.tar.gz"
