name = "CUTEst"
uuid = "1b53aba6-35b6-5f92-a507-53c67d53f819"
version = "1.0.3"

[deps]
CUTEst_jll = "bb5f6f25-f23d-57fd-8f90-3ef7bad1d825"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
SIFDecode_jll = "54dcf436-342f-53ea-8005-3708a1ae6c8c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
CUTEst_jll = "=2.4.0"
Combinatorics = "1.0"
DataStructures = "0.18"
JSON = "0.21"
NLPModels = "0.21.3"
Quadmath = "0.5.10"
SIFDecode_jll = "2.6.1"
julia = "^1.6.0"

[extras]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLPModelsTest = "7998695d-6960-4d3a-85c4-e1bceb8cd856"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Combinatorics", "LinearAlgebra", "NLPModelsTest", "Random", "SparseArrays", "Test"]
