[deps]
Clang = "40e3b903-d033-50b4-a0cc-940c62c95e31"
CUTEst_jll = "bb5f6f25-f23d-57fd-8f90-3ef7bad1d825"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"

[compat]
julia = "1.6"
CUTEst_jll = "2.2.2"
